// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnF-5YOkXB2Wp4c3prYkCb18C69fBWnzw',
    appId: '1:814219916762:web:510197003856861e297ce3',
    messagingSenderId: '814219916762',
    projectId: 'kharcha-f360a',
    authDomain: 'kharcha-f360a.firebaseapp.com',
    storageBucket: 'kharcha-f360a.firebasestorage.app',
    measurementId: 'G-W10QYNMW33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ2nbQJK8ywT4VKAy6LQjnf5TFcYRhXTo',
    appId: '1:814219916762:android:c21ce970c49190fb297ce3',
    messagingSenderId: '814219916762',
    projectId: 'kharcha-f360a',
    storageBucket: 'kharcha-f360a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5R3glyMa7apKweQwnI5efSBqrtsaAldw',
    appId: '1:814219916762:ios:ede3a421c07e51ec297ce3',
    messagingSenderId: '814219916762',
    projectId: 'kharcha-f360a',
    storageBucket: 'kharcha-f360a.firebasestorage.app',
    iosBundleId: 'com.skillpath.kharchaApp',
  );
}
